config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')), 
    path('products/',include('products.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path 
from .views import IndexView,CategoryView

app_name = 'main' #=> main:index
urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('<str:category_name>/category',CategoryView.as_view(),name='category'),
]

products/urls.py
from django.urls import path
from .views import new_product,product_detail,product_update,product_delete,new_comment,delete_comment


app_name = 'products' #{%url 'products:'new'%}
urlpatterns = [
    path('new/',new_product,name='new'),
    path('<int:product_id>/detail/',product_detail,name='detail'),
    path('<int:product_id>/update/',product_update,name='update'),
    path('<int:product_id>/delete/',product_delete,name='delete'),
    path('<int:product_id>/comment/<int:comment_id>delete/',delete_comment,name='comment_delete'),
    path('<int:product_id>/comment/new/',new_comment,name='comment_new'),


]

users/urls.py
from .views import SignupView,ProfileView,UpdateProfileView,AddRemuveSavedView,SevedView,RecentlyViwedView
from django.urls import path

app_name= 'users'
urlpatterns = [
    path('signup/',SignupView.as_view(), name='signup'),
    path('profile/<str:username>/',ProfileView.as_view(), name='profile'),
    path('update/',UpdateProfileView.as_view(), name='update'),
    path('addremoveseved/<int:product_id>',AddRemuveSavedView.as_view(),name='addremovesaved'),
    path('savads/',SevedView.as_view(),name='saveds'),
    path('recently-viewed/',RecentlyViwedView.as_view(),name='recently_viewed')

    ]

products/models.py
from django.db import models
from users.models import CustomUser
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=160)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(max_digits=10000000, decimal_places=2)
    address = models.CharField(max_length=150)
    phone_number= PhoneNumberField(unique=True)
    tg_username = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True) 

    def __str__(self) :
        return str(self.title)
    
    class Meta:
        ordering = ('-id',)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_images")


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)


    def __str__(self):
        return "Comment of"+str(self.author.username)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}E-Shops{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    
</head>
<style>
  img{
    object-fit: contain;
  }
</style>
<body class="bg-blue">
   
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'main:index'%}">E-Shops</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <div class="btn-group">
                  <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-disabled="false">
                    Categories
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                    {% for i in categories %}
                    <li><a class="dropdown-item" href="{% url 'main:category' i.name %}">{{ i.name }}</a></li>

                    {% endfor%}
                    
                  </ul>
                </div>            
               </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:new' %}">Add Product</a>
            
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'users:saveds' %}">Saveds</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                  
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:recently_viewed' %}">Recently Viwed</a>
              </li>
            </ul>
            <div class="btn-group">
            <form class="d-flex" role="search">
              <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if request.user.is_authenticated %}           
            <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
              <img src="{{ request.user.avatar.url}}" width="35" height="35" class="rounded" alt="">
            </button>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg" >
              <li><a class="dropdown-item" href="#">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              <li><a class="dropdown-item" href="http://127.0.0.1:8000/admin/">Admin panel</a></li>
            </ul>
            {% else %}
             <a href="{% url 'login'%}" class="btn btn-primary">Login</a>
             <a href="{% url 'users:signup'%}" class="btn btn-primary">SignUp</a> 
             {% endif %} 
            </div>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock content %}

      <div class="container">
        {% if message %}
       
        <div style="z-index: 312;" class="shadow-sm position-fixed end-0 bottom-0 mt4">
          {% for message in messages %}
            <div style="width: 20rem; opacity:0.9" class="m-3 alert alert-{{message.tags}}" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
      </div>


      <div class="footer m-5 mb-3">
        <center class="text-muted">Xikmatulla | 2023</center>
        <center class="text-muted">Telefon | +99 899 450 77 73</center>

      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/category.html
{% extends "base.html"%}
{% load static %}
{% load django_bootstrap5 %}

{% block tutle%}
    E-shop - {{ category }}

{% endblock tutle%}


{% block content %}
    <div class="container">
        <div class="w-100 mt-4">
            <h4 class="d-black">Recently Products in {{ category }}</h4>
            <div class="d-flex flex-wrap justify-content-between">
                {% for i in products %}
               
                <div class="card border-0 shadow-sm d-inline-black m-1 mt-3" style="width:16.5rem;">
                    {% if i.productimage_set.exists %}                  
                    <img height="200" class="card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="123">
                    {% else %}
                    <img height="200" class="card-img-top" src="" alt="">
                    {% endif %}
                    <dev class="card-body">
                    <h6 class="align-center card-text">{{i.title}}</h6>
                    <span class="center cart-text"><smal>{{i.price}}</small>$</span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i>
                        <a href="#" class="btn btn-outline-primary">Details</a>
                        
                       
                    </div>
                </div> 
            </div>
             {% endfor %}
        </div>
    </div>




{% endblock content %}

templates/index.html
{% extends "base.html"%}
{% load static %}
{% load django_bootstrap5 %}

{% block title%}
    E-shop - Home

{% endblock title%}


{% block content %}
    {% comment %} <h1 style="text-align: center; color: brown;">Online Shops</h1>

    <div class="container">
        <h4 class="d-black">Recently Products</h4>
        <div class="row">
        {% for i in products %}
            <div class="col-md-4 mx-2">
                <div class="card  border border-0 shadow-sm d-inline m-1 mt-3" style="width: 30%;display: inline;">
                    {% if i.productimage_set.exists %}                  
                    <img height="200" class="card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="123">
                    {% else %}
                    <img height="200" class="card-img-top" src="" alt="">
                    {% endif %}
                    <dev class="card-body">
                    <h6 class="align-center card-text">{{i.title}}</h6>
                    <span class="center cart-text"><smal>{{i.price}}</small>$</span>                                                
                    <div class="buttons d-flex flex-wrap justify-content-between ">    
                        <a href="{% url 'users:addremovesaved' i.id%}" >&#9989; </a></i> 
                        <i class="bi bi-bookmark-fill"><a href="{% url 'users:addremovesaved' i.id%}" ></a></i> </i>
                                            
                        <a href="{% url 'products:detail' i.id%}" class="btn btn-outline-primary">Details</a>

                        
            
                        
                        
                    </div>
                </div> 
            </div>
        {% endfor %}
    </div>
    </div> {% endcomment %}

         <!-- Product Cart Start -->
         <div class="container">
            <div class=" w-100 mt-4">
                <h4 class="d-block text-center text-primary" >Recently Products</h4>
                <div class="d-flex flex-wrap justify-content-between">
                    {% for i in products%}
                    
                    <!-- Product Cart Start -->
                    <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                        {% if i.productimage_set.exists%}
                        <img height="200" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                        {% else %}
                        <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                        {% endif%}
                        <div class="card-body text-center">
                            <h6 class="align-center card-title">{{i.title}}</h6>
                            <span class="center card-text"><small>{{i.price}}</small>$</span>
                            <div class="buttons d-flex flex-wrap justify-content-between mx-4 mt-2 ">
                                <i class="bi bi-boo1kmark-fill text-center mx-4 mt-3"><a href="{% url 'users:addremovesaved' i.id%}">&#9989; </a></i> 
                                <a href="{% url 'products:detail' i.id%} " class="btn btn-outline-primary" >Details</a>
                            </div>
                        </div>
                    </div>  
                    <!-- Product Cart End -->
                    {% endfor %}
 
                </div>
            </div>
        </div>
        <!-- Product Cart End -->

{% endblock content %}

templates/product_delete.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% block title %}
 Delete Product-{{product.title}}
{% endblock title %}


{% block content %}
    <div class="container">
        <div class="col"></div>
        <div class="col-md-6 offset-3 my-5">
            <h2> Are you to delete - {{product.title}}</h2>
            
            <form method = "post" enctype="multipart/form-data">
            

                <button type = "submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-secondary" href="{% url 'products:detail' product.id %}"> Back Details</a>
            </forma>
        </div>
        <div class="col"></div>
    </div>
{% endblock content %}

templates/product_detail.html
{% extends "base.html" %}
{% block title %}
E-Shop - {{product.title}}
{% endblock title %}

{% block content %}
<!--  
 <div class="col-md-6 offset-3">
    <div clss="container">
        <div class=" w-100 mt-5">
            <div class="row shadow-sm ">
                <div class="col-4 p-3">
                    <div class = "carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel"> 
                        <div class = "carousel-inner">
                            {% for picture in product.productimage_set.all%}
                            {% if picture == product.productimage_set.all.first %}

                            <div class="carousel-item active thumbnail shadow-sm">
                                <img class="d-block w-100" width='400' height='270' src="{{picture.image.url}}" alt="rasm bor">
                            </div>
                            {% else %}
                            <div class="carousel-item active thumbnail shadow-sm">
                                <img class="d-block w-100" width='400' height='270' src="{{picture.image.url}}" alt="rasm bor">
                            </div>
                            {% endif%}
                            {% endfor %}
                        </div>
                        <button class= "carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slid="priv">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visualliy-hidden">Previous</span>
                        </button>
                        <button class= "carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slid="next">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visualliy-hidden">Next</span>
                        </button>    
                    </div>
                    <div class="col-7 p-5">
                        <h4>Kompyuter Sotiladi</h4>
                        <p class="test-muted"><a href="#">@tillo704</a>|24.05.2023</p>
                        <p>Lorem ipsum dolor sit amet consectetur adisicing elit</p>
                        <div class="contact mt-4">
                            <a class="btn btn-warning" href="#">Edit Details</a>                        
                            <a class="btn btn-primary" href="{{customuser.email}}">Email</a>                        
                            <a class="btn btn-primaryg" href="tel:{{product.phone_number}}">Call</a>                        
                            <a class="btn btn-primary" href="http://t.me/@{{produqt.tg_username}}">Telegram</a>                        
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class=col-8 mt-5>
                        <h6>In This Category</h6>
                        <div class="d-flex flex-wrap justify-content-between">
                            <div class = "card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width:14rem;">
                                <img height="190" class="card-img-top" src="#" alt="">
                                <div class="card-body">
                                    <h6 class="align-center card-title">Laptop is selling!</h6>
                                    <span class="center card-text">10000</span>
                                    <div class="button d-flex flex-wrap justify-content-between">
                                        <i class="bi bi-bookmark-fill"></i>
                                        <a href="#" class="btn btn-outline-primary">Details</a>
                                    </div>
    
                                </div>
                            </div>
                        </div>
                        <div class="col-4 mt-5 shadow-sm">
                            <h6 class="pt-2">Add comment</h6>
                            <form action="#" method="post" class="input-group">
                                <input class="form-control" name="body" type="text" placeholder="Type your comment..." aria-describedby="">
                                <button class="btn btn-outline-success" type="submit" id="button-addon">Send</button>
                            </form>
                        </div>
    
                    </div>
                </div>
            </div>
    
        </div>
    </div>
 </div> -->
 <div class="container">
    <div class=" w-100 mt-5 ">
        <div class="row shadow-sm ">
            <div class="col-4 p-3">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for picture in product.productimage_set.all%}
                        {% if picture == product.productimage_set.all.first %}
                            <div class="carousel-item active thumbnail shadow-sm ">
                                <img class="d-block w-100 " width="400" height="270" src="{{picture.image.url}}" alt="">
                            </div>
                        {% else %}
                            <div class="carousel-item thumbnail shadow-sm">
                                <img class="d-block w-100  " width="400" height="270" src="{{picture.image.url}}" alt="">
                            </div>
                        {% endif%}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
              </div> 
            </div>
            <div class="col-7 p-5 ">
                <h4>{{product.title}}</h4>
                <p class="test-muted"><a href="{% url 'users:profile' product.author.username%}">@{{product.author.username}}</a> | 25.01.2023</p>
                <p >{{product.description|safe}}</p>
                <div class="contact mt-4 ">
                    {% if request.user == product.author %}
                    <a class="btn btn-warning" href="{% url 'products:update' product.id%}">Edit details</a>
                    {% endif %}
                    <a class="btn btn-primary" href="{{customuser.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{product.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{produqt.tg_username}}">Telegram</a>
                </div>
            </div>
        </div>
        <div class="row ">  
            <div class="col-8 mt-5" >
                <h6  >In This Category</h6> 
                <div class="d-flex flex-wrap justify-content-between">
                    {% for i in product.cotegory.product_set.all %}
                    {% if product != i%}
                    <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 14rem;" >
                        <img height="190" class=" card-img-top" src="{{i.product.image_set.all.first.image.url}}" alt="">
                        <div class="card-body">
                            <h6 class="align-center card-title">{{ i.title }}</h6>
                            <span class="center card-text">{{ i.price }} $</span>
                            <div class="buttons d-flex flex-wrap justify-content-between ">
                                <i class="bi bi-bookmark-fill"></i> 
                                <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                            </div>
                        </div>
                    </div> 
                    {% endif %} 
                    {% endfor %}
                </div>
            </div>
            <div class="col-4 mt-5 shadow-sm ">
                <h6 class="pt-2" >Add comment</h6>
                <form action="{% url 'products:comment_new' product.id %}" method="post" class="input-group">{% csrf_token %}
                    <input class="form-control" name="body" type="text" placeholder="Type your comment..." aria-describedby="'button-addon" >
                    <button class="btn btn-outline-success" type="submit" id="button-addon">Send</button>
                </form>  
                <hr>
                <h6>Comments</h6>
                {% for comment in product.comment_set.all%}
                <small class="text-muted" >@{{comment.author}} | {{comment.date}}</small>
                {% if request.user == comment.author %}
                    <p>{{ comment.body }} <small><a href="{% url 'products:comment_delete' product.id comment.id %}">Delete</a></small></p>
                {%endif%}
                
                {% endfor %}  
            </div>
        </div>

</div>
</div>



{% endblock content %}

templates/product_update.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% block title %}
 Update Product-{{pr.title}}
{% endblock title %}


{% block content %}
    <div class="container">
        <div class="col"></div>
        <div class="col-md-6 offset-3 my-5">
            <h2> Update Product - {{pr.title}}</h2>
            
            <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form|crispy }}

                <button type = "submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-danger" href="{% url 'products:delete' pr.id %}">Delete</a>
                <a class="btn btn-secondary" href="{% url 'products:detail' pr.id %}"> Back Details</a>
            </forma>
        </div>
        <div class="col"></div>
    </div>
{% endblock content %}

templates/profile.html
{% extends "base.html"%}
{% block title %}
E-Shops - {{customuser}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-5">
            <div class="row">
                <div class="col-2 m-3">
                    <img class="img-thumbnail" width="150" height="180" scr="{{customuser.avatar.url}}" alt="123">
                </div>
                <div class="col-8 m-3">
                    <h2>{{customuser.get_full_name}}</h2>
                    <p class="text-muted">@{{customuser.username}} | {{customuser.email}}</p>
                    {%if customuser == request.user%}                    
                        <a class="btn btn-warning" href="{% url 'users:update' %}">Edit Details</a>
                        <a class="btn btn-danger" href="{% url 'password_change'%}">Update Password</a>
                    {%endif%}
                    <a class="btn btn-primary" href="{ mailto:{{customer.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{customer.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{customuser.tg_username}}">Telegram</a>
                   

                </div>
            </div>
        
        </div>
    </div>

</div>
{% endblock content %}

templates/profile_update.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% block title %}
 Update_profile - {{request.user}}
{% endblock title %}


{% block content %}
    <div class="container">
        <div class="col"></div>
        <div class="col-md-6 offset-3 my-5">
            <h2> Update_profile - {{request.user}} </h2>
            
            <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form|crispy }}

                <button type = "submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-secondary" href="{% url 'users:profile' request.user %}"> Back</a>
            </forma>
        </div>
        <div class="col"></div>
    </div>
{% endblock content %}

templates/recently_viewed.html
{% extends "base.html"%}
{% load static %}
{% load django_bootstrap5 %}

{% block title%}
    E-shop - Recently Viewed

{% endblock title%}


{% block content %}
    <div class="container">
        <div class="w-100 mt-4 ">
            <h4 class="d-black">Recently Viwed Products</h4>
            <div class="d-flex flex-wrap justify-content-between">
                {% for i in products %}
               
                <div class="card border-0 shadow-sm d-inline-black m-1 mt-3" style="width:16.5rem;">
                    {% if i.productimage_set.exists %}                  
                    <img height="200" class="card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="123">
                    {% else %}
                    <img height="200" class="card-img-top" src="" alt="">
                    {% endif %}
                    <dev class="card-body">
                    <h6 class="align-center card-text">{{i.title}}</h6>
                    <span class="center cart-text"><smal>{{i.price}}</small>$</span>                                                
                    <div class="buttons d-flex flex-wrap justify-content-between " >    
                        <a href="{% url 'users:addremovesaved' i.id%}" >&#9989; </a></i> 
                        <i class="bi bi-bookmark-fill"><a href="{% url 'users:addremovesaved' i.id%}" ></a></i> </i>
                                         
                        <a href="{% url 'products:detail' i.id%}" class="btn btn-outline-primary">Details</a>
           
                        
                       
                    </div>
                </div> 
            </div>
             {% endfor %}
        </div>
    </div>




{% endblock content %}

templates/saveds.html
{% extends "base.html"%}
{% load static %}
{% load django_bootstrap5 %}

{% block tutle%}
    E-shop - Saved Products of  @{{request.user}}

{% endblock tutle%}


{% block content %}
    {% comment %} <div class="container">         
        <div class="w-100 mt-4">
            <div class="row">
                <h4 class="d-black">Saved Products of  @{{request.user}}</h4>
                <div class="row">
                    <div class="col-md-4 mx-2">       
                        {% for i in saved %}             
                        <div class="card  border border-0 shadow-sm d-inline m-1 mt-3" style="width: 30%;display: inline;">
                            {% if i.product.productimage_set.exists %}                  
                            <img height="200" class="card-img-top" src="{{i.product.productimage_set.all.first.image.url}}" alt="123">
                            {% else %}
                            <img height="200" class="card-img-top" src="" alt="">
                            {% endif %}
                            <dev class="card-body">
                                <h6 class="align-center card-text">{{i.product.title}}</h6>
                                <span class="center cart-text"><smal>{{i.product.price}}</small>$</span>                                                
                                    <div class="buttons d-flex flex-wrap justify-content-between ">         
                                        <i class="fa fa-bookmark-o" style="font-size:36px"></i>
                                        <i class="bi bi-bookmark-fill"></i>
                                        <a href="{% url 'products:detail' i.product.id %}" class="btn btn-outline-primary">Details</a>
                                    </div>    
                        </div>
                </div> 
            </div>
                      {% endfor %}
        </div>
    </div>
 {% endcomment %}

        <!-- Product Cart Start -->
        <div class="container">
            <div class=" w-100 mt-4">
                <h4 class="d-block text-center" >Saved Products of  @{{request.user}}</h4>
                <div class="d-flex flex-wrap justify-content-between">
                    {% for i in saved %} 
                    
                    <!-- Product Cart Start -->
                    <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                        {% if i.product.productimage_set.exists %} 
                        <img height="200" class=" card-img-top" src="{{i.product.productimage_set.all.first.image.url}}" alt="">
                        {% else %}
                        <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                        {% endif%}
                        <div class="card-body text-center">
                            <h6 class="align-center card-title">{{i.product.title}}</h6>
                            <span class="center card-text"><small>{{i.product.price}}</small>$</span>
                            <div class="buttons d-flex flex-wrap justify-content-between ">
                                <i class="bi bi-boo1kmark-fill text-center"><a href="{{index}}">&#9989; </a></i> 
                                <a href="{% url 'products:detail' i.product.id %} " class="btn btn-outline-primary" >Details</a>
                            </div>
                        </div>
                    </div>  
                    <!-- Product Cart End -->
                    {% endfor %}
    
                </div>
            </div>
        </div>
        <!-- Product Cart End -->
    

  


{% endblock content %}